import { AuthProvider } from "@/lib/authContext";
import { SavesProvider } from "@/lib/savesContext";
import Sidebar from "@/components/Sidebar";
import BottomNav from "@/components/BottomNav";
import TopNav from "@/components/TopNav";
import AppShell from "@/components/AppShell";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased">
        <AuthProvider>
          <SavesProvider>
            <AppShell nav={<><TopNav /><Sidebar /><BottomNav /></>}>
              {children}
            </AppShell>
          </SavesProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
